autoInstallPeers: false
allowBuilds:
  core-js: false
  esbuild: false
  puppeteer: false
  simple-git-hooks: true
  spawn-sync: false
overrides:
  yauzl: 3.3.1
patchedDependencies:
  lodash: patches/lodash.patch
  lodash-es: patches/lodash-es.patch
