name: dev

on:
  push:
    branches:
    - dev
    - fix/*
    - feat/*
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform(amo,cws,xpi,edge,crx)'
        required: true
        type: string
      version:
        description: 'Version'
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_changes:
    runs-on: ubuntu-24.04
    outputs:
      locale_changed: ${{ steps.filter.outputs.locale }}
      docs_changed: ${{ steps.filter.outputs.docs }}
      src_changed: ${{ steps.filter.outputs.src }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          base: ${{ github.ref_name }}
          filters: |
            locale:
              - 'locale/**'
            docs:
              - 'docs/**'
            src:
              - 'src/**'
              - 'public/**'
              - 'scripts/**'
              - 'tests/**'
              - 'patches/**'
              - 'rsbuild.config.ts'
              - 'pnpm-lock.yaml'

  unit-test:
    needs: check_changes
    runs-on: ubuntu-24.04
    if: ${{ needs.check_changes.outputs.src_changed == 'true' || github.event_name == 'workflow_dispatch' }}
    steps:
    - uses: actions/checkout@v6
    - uses: pnpm/action-setup@v6
      with:
        version: 11.11.0
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm i --frozen-lockfile
    - name: Test unit tests
      run: npm run test:unit

  build:
    needs: check_changes
    runs-on: ubuntu-24.04
    if: ${{ needs.check_changes.outputs.src_changed == 'true' || github.event_name == 'workflow_dispatch' }}
    steps:
    - uses: actions/checkout@v6
    - name: Inject Env
      run: |
        echo "INPUT_PLATFORM=${{ github.event.inputs.platform }}" >> $GITHUB_ENV
        echo "INPUT_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
    - uses: pnpm/action-setup@v6
      with:
        version: 11.11.0
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm i --frozen-lockfile
    - name: Get snapshot version
      uses: FirefoxBar/extension-packer@action
      with:
        script: ${{ github.workspace }}/scripts/get-snapshot-version.mjs
      env:
        TOKEN: ${{ secrets.SNAPSHOT_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build And Test
      uses: ./.github/actions/build-and-test
    - name: Publish snapshot
      uses: FirefoxBar/extension-packer@action
      with:
        script: ${{ github.workspace }}/scripts/pack.mjs
      env:
        AMO_KEY: ${{ secrets.ORG_AMO_KEY }}
        AMO_SECRET: ${{ secrets.ORG_AMO_SECRET }}
        CRX_PRIV_KEY: ${{ secrets.CRX_PRIV_KEY }}
        PACK_PLATFORM: xpi,crx
    - name: Upload snapshot release
      uses: actions/upload-artifact@v7
      with:
        name: release
        retention-days: 7
        path: temp/release

  sync-locale:
    needs: check_changes
    runs-on: ubuntu-24.04
    if: ${{ needs.check_changes.outputs.locale_changed == 'true' }}
    steps:
    - uses: actions/checkout@v6
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: Sort
      run: node ./locale/sort-origin.js
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: sync-locale
        folder: locale
        clean: false
        commit-message: '[skip ci] sync locale'

  build-docs:
    needs: check_changes
    if: ${{ needs.check_changes.outputs.docs_changed == 'true' }}
    uses: ./.github/workflows-part/build-docs.yml
    secrets: inherit
    with:
      is_prod: false
