name: main

on:
  push:
    branches:
    - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_changes:
    runs-on: ubuntu-24.04
    outputs:
      docs_changed: ${{ steps.filter.outputs.docs }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          base: ${{ github.ref_name }}
          filters: |
            docs:
              - 'docs/**'

  build-docs:
    needs: check_changes
    if: ${{ needs.check_changes.outputs.docs_changed == 'true' }}
    uses: ./.github/workflows/build-docs.yml
    secrets: inherit
    with:
      is_prod: false
