name: main

on:
  push:
    branches:
    - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_changes:
    runs-on: ubuntu-24.04
    outputs:
      docs_changed: ${{ steps.filter.outputs.docs }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          base: ${{ github.ref_name }}
          filters: |
            docs:
              - 'docs/**'

  build-docs:
    needs: check_changes
    runs-on: ubuntu-24.04
    if: ${{ needs.check_changes.outputs.docs_changed == 'true' }}
    steps:
    - uses: actions/checkout@v6
    - uses: pnpm/action-setup@v6
      with:
        version: 11.11.0
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: Install dependencies
      run: |
        cd $GITHUB_WORKSPACE/docs
        pnpm i --frozen-lockfile --ignore-workspace --ignore-scripts
    - name: Build
      run: |
        cd $GITHUB_WORKSPACE/docs
        npm run build
        cp $GITHUB_WORKSPACE/scripts/www/* $GITHUB_WORKSPACE/docs/doc_build/
    - name: Upload
      uses: actions/upload-artifact@v7
      with:
        name: docs
        retention-days: 1
        path: docs/doc_build

  deploy-docs-cloudflare:
    needs: build-docs
    runs-on: ubuntu-24.04
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: Download
      uses: actions/download-artifact@v5
      with:
        name: docs
        path: docs
    - name: Deploy Cloudflare Pages
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.ORG_CF_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.ORG_CF_ACCOUNT_ID }}
      run: npx wrangler@3 pages deploy docs --project-name=${{ vars.CF_PAGE_NAME }}

  deploy-docs-eo:
    needs: build-docs
    runs-on: ubuntu-24.04
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: Download
      uses: actions/download-artifact@v5
      with:
        name: docs
        path: docs
    - name: Deploy EdgeOne Pages
      run: npx edgeone pages deploy $GITHUB_WORKSPACE/docs -n ${{ vars.EO_PAGE_NAME }} -t ${{ secrets.ORG_EO_PAGE_TOKEN }}
